# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Movieskip' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Movieskip
  
    pod 'Firebase/Firestore'
    pod 'Firebase/Auth'
    pod 'Firebase/Storage'
    pod 'Firebase/Core'
    pod 'FirebaseUI/Auth'
    pod 'FirebaseUI/Google'
    pod 'FBSDKLoginKit'
    
    pod 'SDWebImage', '~>4.4.2'
    pod 'SwiftyJSON', '~> 4.0'
    pod 'Alamofire', '~> 5.2'

end

post_install do |pi|
    pi.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
      end
    end
end
